// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ch3 from "../../src/cs3110/Ch3.mjs";
import * as Test from "rescript-test/src/Test.mjs";

Test.test("computes product of an empty list", (function (param) {
        Test.assertion(undefined, undefined, (function (x, y) {
                return x === y;
              }), Ch3.product(/* [] */0), 1);
      }));

Test.test("computes product of list with one item", (function (param) {
        Test.assertion(undefined, undefined, (function (x, y) {
                return x === y;
              }), Ch3.product({
                  hd: 1,
                  tl: /* [] */0
                }), 1);
      }));

Test.test("computes product of list with two items", (function (param) {
        Test.assertion(undefined, undefined, (function (x, y) {
                return x === y;
              }), Ch3.product({
                  hd: 1,
                  tl: {
                    hd: 2,
                    tl: /* [] */0
                  }
                }), 2);
      }));

Test.test("computes product of list with three items", (function (param) {
        Test.assertion(undefined, undefined, (function (x, y) {
                return x === y;
              }), Ch3.product({
                  hd: 1,
                  tl: {
                    hd: 2,
                    tl: {
                      hd: 3,
                      tl: /* [] */0
                    }
                  }
                }), 6);
      }));

export {
  
}
/*  Not a pure module */
