// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Ch3 from "../../src/cs3110/Ch3.mjs";
import * as Vitest from "rescript-vitest/src/Vitest.mjs";
import * as Vitest$1 from "vitest";

Vitest.test("computes product of an empty list", undefined, (function (t) {
        t.assertions(1);
        Vitest$1.expect(Ch3.product(/* [] */0)).toBe(1);
      }));

Vitest.test("computes product of list with one item", undefined, (function (t) {
        t.assertions(1);
        Vitest$1.expect(Ch3.product({
                    hd: 1,
                    tl: /* [] */0
                  })).toBe(1);
      }));

Vitest.test("computes product of list with two items", undefined, (function (t) {
        t.assertions(1);
        Vitest$1.expect(Ch3.product({
                    hd: 1,
                    tl: {
                      hd: 2,
                      tl: /* [] */0
                    }
                  })).toBe(2);
      }));

Vitest.test("computes product of list with three items", undefined, (function (t) {
        t.assertions(1);
        Vitest$1.expect(Ch3.product({
                    hd: 1,
                    tl: {
                      hd: 2,
                      tl: {
                        hd: 3,
                        tl: /* [] */0
                      }
                    }
                  })).toBe(6);
      }));

export {
  
}
/*  Not a pure module */
