// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Caml_option = require("rescript/lib/js/caml_option.js");

function last(_list) {
  while(true) {
    var list = _list;
    if (!list) {
      return ;
    }
    var rest = list.tl;
    if (!rest) {
      return Caml_option.some(list.hd);
    }
    _list = rest;
    continue ;
  };
}

console.log(last(/* [] */0) === undefined);

console.log(last({
          hd: 1,
          tl: /* [] */0
        }) === 1);

console.log(last({
          hd: 1,
          tl: {
            hd: 2,
            tl: /* [] */0
          }
        }) === 2);

console.log(last({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }) === 3);

function lastTwo(_list) {
  while(true) {
    var list = _list;
    if (!list) {
      return ;
    }
    var rest = list.tl;
    if (!rest) {
      return ;
    }
    if (!rest.tl) {
      return [
              list.hd,
              rest.hd
            ];
    }
    _list = rest;
    continue ;
  };
}

console.log(lastTwo(/* [] */0) === undefined);

console.log(lastTwo({
          hd: 1,
          tl: /* [] */0
        }) === undefined);

console.log(Caml_obj.equal(lastTwo({
              hd: 1,
              tl: {
                hd: 2,
                tl: /* [] */0
              }
            }), [
          1,
          2
        ]));

console.log(Caml_obj.equal(lastTwo({
              hd: 1,
              tl: {
                hd: 2,
                tl: {
                  hd: 3,
                  tl: /* [] */0
                }
              }
            }), [
          2,
          3
        ]));

function at(_list, _n) {
  while(true) {
    var n = _n;
    var list = _list;
    if (!list) {
      return ;
    }
    if (n === 0) {
      return Caml_option.some(list.hd);
    }
    _n = n - 1 | 0;
    _list = list.tl;
    continue ;
  };
}

console.log(at(/* [] */0, 0) === undefined);

console.log(at({
          hd: 1,
          tl: /* [] */0
        }, 0) === 1);

console.log(at({
          hd: 1,
          tl: /* [] */0
        }, 1) === undefined);

console.log(at({
          hd: 1,
          tl: {
            hd: 2,
            tl: /* [] */0
          }
        }, 0) === 1);

console.log(at({
          hd: 1,
          tl: {
            hd: 2,
            tl: /* [] */0
          }
        }, 1) === 2);

console.log(at({
          hd: 1,
          tl: {
            hd: 2,
            tl: /* [] */0
          }
        }, 2) === undefined);

console.log(at({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }, 0) === 1);

console.log(at({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }, 1) === 2);

console.log(at({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }, 2) === 3);

console.log(at({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }, 3) === undefined);

function length(list) {
  var _list = list;
  var _acc = 0;
  while(true) {
    var acc = _acc;
    var list$1 = _list;
    if (!list$1) {
      return acc;
    }
    _acc = acc + 1 | 0;
    _list = list$1.tl;
    continue ;
  };
}

console.log(length(/* [] */0) === 0);

console.log(length({
          hd: 1,
          tl: /* [] */0
        }) === 1);

console.log(length({
          hd: 1,
          tl: {
            hd: 2,
            tl: /* [] */0
          }
        }) === 2);

console.log(length({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }) === 3);

exports.last = last;
exports.lastTwo = lastTwo;
exports.at = at;
exports.length = length;
/*  Not a pure module */
