// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function last(_list) {
  while (true) {
    let list = _list;
    if (list === 0) {
      return;
    }
    let rest = list.tl;
    if (rest === 0) {
      return Primitive_option.some(list.hd);
    }
    _list = rest;
    continue;
  };
}

console.log(last(/* [] */0) === undefined);

console.log(last({
  hd: 1,
  tl: /* [] */0
}) === 1);

console.log(last({
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
}) === 2);

console.log(last({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}) === 3);

function lastTwo(_list) {
  while (true) {
    let list = _list;
    if (list === 0) {
      return;
    }
    let rest = list.tl;
    if (rest === 0) {
      return;
    }
    if (rest.tl === 0) {
      return [
        list.hd,
        rest.hd
      ];
    }
    _list = rest;
    continue;
  };
}

console.log(lastTwo(/* [] */0) === undefined);

console.log(lastTwo({
  hd: 1,
  tl: /* [] */0
}) === undefined);

console.log(Primitive_object.equal(lastTwo({
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
}), [
  1,
  2
]));

console.log(Primitive_object.equal(lastTwo({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}), [
  2,
  3
]));

function at(_list, _n) {
  while (true) {
    let n = _n;
    let list = _list;
    if (list === 0) {
      return;
    }
    if (n === 0) {
      return Primitive_option.some(list.hd);
    }
    _n = n - 1 | 0;
    _list = list.tl;
    continue;
  };
}

console.log(at(/* [] */0, 0) === undefined);

console.log(at({
  hd: 1,
  tl: /* [] */0
}, 0) === 1);

console.log(at({
  hd: 1,
  tl: /* [] */0
}, 1) === undefined);

console.log(at({
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
}, 0) === 1);

console.log(at({
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
}, 1) === 2);

console.log(at({
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
}, 2) === undefined);

console.log(at({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}, 0) === 1);

console.log(at({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}, 1) === 2);

console.log(at({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}, 2) === 3);

console.log(at({
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}, 3) === undefined);

function length(_countOpt, _list) {
  while (true) {
    let countOpt = _countOpt;
    let list = _list;
    let count = countOpt !== undefined ? countOpt : 0;
    if (list === 0) {
      return count;
    }
    _list = list.tl;
    _countOpt = count + 1 | 0;
    continue;
  };
}

console.log(length(undefined, /* [] */0) === 0);

console.log(length(undefined, {
  hd: 1,
  tl: /* [] */0
}) === 1);

console.log(length(undefined, {
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
}) === 2);

console.log(length(undefined, {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}) === 3);

function reverse(_accOpt, _list) {
  while (true) {
    let accOpt = _accOpt;
    let list = _list;
    let acc = accOpt !== undefined ? accOpt : /* [] */0;
    if (list === 0) {
      return acc;
    }
    _list = list.tl;
    _accOpt = {
      hd: list.hd,
      tl: acc
    };
    continue;
  };
}

console.log(reverse(undefined, /* [] */0) === /* [] */0);

console.log(Primitive_object.equal(reverse(undefined, {
  hd: 1,
  tl: /* [] */0
}), {
  hd: 1,
  tl: /* [] */0
}));

console.log(Primitive_object.equal(reverse(undefined, {
  hd: 1,
  tl: {
    hd: 2,
    tl: /* [] */0
  }
}), {
  hd: 2,
  tl: {
    hd: 1,
    tl: /* [] */0
  }
}));

console.log(Primitive_object.equal(reverse(undefined, {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
}), {
  hd: 3,
  tl: {
    hd: 2,
    tl: {
      hd: 1,
      tl: /* [] */0
    }
  }
}));

export {
  last,
  lastTwo,
  at,
  length,
  reverse,
}
/*  Not a pure module */
