// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_option = require("rescript/lib/js/caml_option.js");

function last(_list) {
  while(true) {
    var list = _list;
    if (!list) {
      return ;
    }
    var rest = list.tl;
    if (!rest) {
      return Caml_option.some(list.hd);
    }
    _list = rest;
    continue ;
  };
}

function lastTwo(_list) {
  while(true) {
    var list = _list;
    if (!list) {
      return ;
    }
    var rest = list.tl;
    if (!rest) {
      return ;
    }
    if (!rest.tl) {
      return [
              list.hd,
              rest.hd
            ];
    }
    _list = rest;
    continue ;
  };
}

console.log(last(/* [] */0));

console.log(last({
          hd: 1,
          tl: /* [] */0
        }));

console.log(last({
          hd: 1,
          tl: {
            hd: 2,
            tl: /* [] */0
          }
        }));

console.log(last({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }));

console.log(lastTwo(/* [] */0));

console.log(lastTwo({
          hd: 1,
          tl: /* [] */0
        }));

console.log(lastTwo({
          hd: 1,
          tl: {
            hd: 2,
            tl: /* [] */0
          }
        }));

console.log(lastTwo({
          hd: 1,
          tl: {
            hd: 2,
            tl: {
              hd: 3,
              tl: /* [] */0
            }
          }
        }));

exports.last = last;
exports.lastTwo = lastTwo;
/*  Not a pure module */
