// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add1(aList) {
  if (aList) {
    return aList.hd + add1(aList.tl) | 0;
  } else {
    return 0;
  }
}

function add2(_totalOpt, _aList) {
  while(true) {
    var totalOpt = _totalOpt;
    var aList = _aList;
    var total = totalOpt !== undefined ? totalOpt : 0;
    if (!aList) {
      return total;
    }
    _aList = aList.tl;
    _totalOpt = aList.hd + total | 0;
    continue ;
  };
}

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

console.log(add1(myList));

console.log(add2(undefined, myList));

exports.add1 = add1;
exports.add2 = add2;
exports.myList = myList;
/*  Not a pure module */
