// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add1(list) {
  if (list) {
    return list.hd + add1(list.tl) | 0;
  } else {
    return 0;
  }
}

function add2(_totalOpt, _list) {
  while(true) {
    var totalOpt = _totalOpt;
    var list = _list;
    var total = totalOpt !== undefined ? totalOpt : 0;
    if (!list) {
      return total;
    }
    _list = list.tl;
    _totalOpt = list.hd + total | 0;
    continue ;
  };
}

var myList = {
  hd: 1,
  tl: {
    hd: 2,
    tl: {
      hd: 3,
      tl: /* [] */0
    }
  }
};

console.log(add1(myList));

console.log(add2(undefined, myList));

exports.add1 = add1;
exports.add2 = add2;
exports.myList = myList;
/*  Not a pure module */
